[runtime]
sampler = moped
verbosity = standard

[DEFAULT]
2PT_FILE = ${COSMOSIS_3PCF_INTEGRATOR}/data/dv/sim_2pt-NLA-cosmoDESY3.fits
MAP3_FILE = ${COSMOSIS_3PCF_INTEGRATOR}/data/dv/sim_map3-NLA-cosmoDESY3.fits
run_name = map3-all
group_name = moped-compress
output_dir = not-used

[pipeline]
modules =  consistency  bbn_consistency
           camb  fast_pt
           fits_nz  source_photoz_bias
           IA_NLA
           pk_to_cl
           add_intrinsic
           map3_binning
;           fastnc 
;           nc_to_map3
           fastnc_emulate
           map3_like
timing=T
debug=T
priors = ${COSMOSIS_STD_LIB}/examples/des-y3-priors.ini
values = ${COSMOSIS_3PCF_INTEGRATOR}/config/%(GROUP_NAME)s/des-y3-shear-values.ini
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/map3_chi2

[output]
filename = data/moped/moped-%(group_name)s-%(RUN_NAME)s.txt
format=text
privacy = F

%include ${COSMOSIS_3PCF_INTEGRATOR}/config/3pt.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/astrophysical.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmo.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmic-shear.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/linear-power.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/sampler.ini


; replace the settings of included files for this analysis
[map3_binning]
sample_combinations = all
