[runtime]
sampler = multinest
;sampler = polychord
;sampler = test

[DEFAULT]
2PT_DATA_SETS = xip xim
; nz_file = bin_04_desy3_source_nz.dat
; nz_file = 2pt_NG_1101.fits
nz_file = 2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
; nz_file = 3x2pt_test.fits
data_sets = source

[pipeline]
;values = valuesLCDMrafa.ini
values = fixed_vals.ini
;modules = consistency camb sigma8_rs halofit extrapolate fits_nz lens_photoz_width  lens_photoz_bias fast_pt source_photoz_bias IA pk_to_cl add_intrinsic add_eb shear_2pt_eplusb shear_2pt_eminusb choose_xip 2pt_gal_shear shear_m_bias add_pm smallratio_like moments_like
;modules = consistency  fits_nz  source_photoz_bias     shear_3PCF
;modules = consistency camb sigma8_rs halofit growth extrapolate fits_nz IA stitch unbiased_galaxies pk_to_cl ggl_bias add_intrinsic  2pt_like shear_3PCF_like
;modules = consistency camb sigma8_rs growth extrapolate fits_nz IA unbiased_galaxies pk_to_cl ggl_bias add_intrinsic  2pt_like shear_3PCF_like
;modules = consistency sigma8toAs camb  fast_pt 	fits_nz  source_photoz_bias IA  pk_to_cl add_intrinsic 2pt_shear shear_m_bias 2pt_like shear_3PCF_like
modules = consistency camb fast_pt fits_nz  source_photoz_bias IA  pk_to_cl add_intrinsic 2pt_shear shear_m_bias 2pt_like shear_3PCF_like
likelihoods = 2pt shear_3PCF
;extra_output = cosmological_parameters/sigma_8 data_vector/2pt_chi2

[multinest]
;wrapped_params = cosmological_parameters--omega_b   cosmological_parameters--h0
max_iterations=5000
;max_iterations = 1000
multinest_outfile_root=mn_LCDM_10Jan24smallerDV_2plus3
resume=F
; from Joe:- For a quick run:
live_points=250
efficiency=0.8
tolerance=0.1
constant_efficiency=F

#my trial
[polychord]
;base_dir = output/y3-polychord-checkpoints
polychord_outfile_root = pl_LCDM_10Jan24_2plus3
resume = F
feedback = 3
fast_fraction = 0.1
live_points = 250
num_repeats = 60
tolerance = 0.05
boost_posteriors = 10.0

[output]
filename=my_2plus3pt_LCDM_10Jan24_smallerDV_chain.txt
format=text

[consistency]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/boltzmann/camb/camb_interface.py
mode = power
lmax = 2500
feedback = 3
accuracyboost = 1.1
do_tensors = T
do_lensing = T
nonlinear = pk
halofit_version = takahashi
zmin_background = 0.
zmax_background = 4.
nz_background = 401
kmin = 1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk = 700

[sigma8toAs]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/kids/sigma8toAs.py

[fast_pt]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/structure/fast_pt/fast_pt_interface.py
do_ia = T
k_res_fac = 0.5
verbose = F

[growth]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/structure/growth_factor/interface.so
zmin = 0.
zmax = 4.
nz = 401

[extrapolate]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/boltzmann/extrapolate/extrapolate_power.py

[fits_nz]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py

[IA]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/intrinsic_alignments/tatt/tatt_interface.py
sub_lowk = F
do_galaxy_intrinsic = F
ia_model = tatt

[pk_to_cl]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/structure/projection/project_2d.py
ell_min_logspaced = 0.1
ell_max_logspaced = 5.0e5
n_ell_logspaced = 100
shear-shear = source-source
shear-intrinsic = source-source
intrinsic-intrinsic = source-source
intrinsicb-intrinsicb = source-source
verbose = F
get_kernel_peaks = F
sig_over_dchi = 20.
shear_kernel_dchi = 10.

;[2pt_shear]
;file = cosmosis-standard-library/shear/cl_to_xi_nicaea/nicaea_interface.so
;input_section_name = shear_cl
;output_section_name = shear_xi
;corr_type = 0

[2pt_shear]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = EB
theta_file = xxxyyy_Nov14.fits
bin_avg = T
input_section_name = shear_cl  shear_cl_bb
output_section_name = shear_xi_plus  shear_xi_minus

[shear_m_bias]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/shear/shear_bias/shear_m_bias.py
m_per_bin = True
cl_section = shear_xi_plus shear_xi_minus
cross_section = galaxy_shear_xi
verbose = F

;[2pt_like]
;file = cosmosis-standard-library/likelihood/2pt/2pt_like.py
;data_file = xxxyyy_Nov14.fits
;cut_zeros = T
;data_sets = shear
;do_plot = F
;gaussian_covariance=F
;number_density_shear_bin =  2.0  2.0  2.0  2.0  2.0
;number_density_lss_bin = 2.0  2.0  2.0
;sigma_e_bin = 0.2  0.2  0.2  0.2  0.2
;survey_area = 1500.0

[2pt_like]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/likelihood/2pt/2pt_point_mass/2pt_point_mass.py
do_pm_marg = True
do_pm_sigcritinv = True
sigma_a = 10000.0
no_det_fac = False
include_norm = True
data_file = xxxyyy_Nov14.fits
data_sets = xip xim
make_covariance = F
covmat_name = COVMAT

[shear_3PCF_like]
file = /Users/gchgomes/Downloads/3PCF_likelihood_smaller.py
path_chains =  Sep12_datavector
key =  all_data

[source_photoz_bias]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

[add_intrinsic]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/shear/add_intrinsic/add_intrinsic.py
shear-shear = T
position-shear = F
perbin = F

[sigma8_rs]
file=cosmosis-standard-library/utility/sample_sigma8/sigma8_rescale.py

[add_magnification]
galaxy-galaxy=False