[runtime]
; sampler = test
; sampler = multinest
sampler = list

[DEFAULT]
; 2PT_DATA_SETS = xip xim
; nz_file = 2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
; data_sets = source

[pipeline]
values = des-y3-shear-values.ini
modules =  consistency  bbn_consistency
           camb  fast_pt
           fits_nz  source_photoz_bias
           IA_NLA
           pk_to_cl
           add_intrinsic
           ;2pt_shear
           ;shear_m_bias
           ;2pt_like
           map3_binning
           fastnc
           nc_to_map3
           map3_like
debug=T
timing=T
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2 data_vector/map3_chi2

[test]
save_dir=${COSMOSIS_3PCF_INTEGRATOR}/output/map3-for-shifted-params
fatal_errors = T

[output]
filename=${COSMOSIS_3PCF_INTEGRATOR}/output/map3-for-shifted-params

[nz_source]
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py
nz_file = ${COSMOSIS_3PCF_INTEGRATOR}/data/2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
data_sets = source

[source_photoz_bias]
file = ${COSMOSIS_STD_LIB}/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

[list]
filename = ${COSMOSIS_3PCF_INTEGRATOR}/config/compress-map3/shifted_params.txt

; dependents
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/3pt.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmo.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/astrophysical.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/linear-power.ini
