[cosmological_parameters]
; omega_m      =  0.1     0.3     0.9
; use narrower range
omega_m      =  0.26736
h0           =  0.709
omega_b      = 0.04826
n_s          = 0.96201
w            =  -1.0

; This is here to test S_8 sampling, not to recommend it.
; Don't just put a flat prior on whatever the most convenient
; parameter is.
S_8          = 0.78719

; Old parameter names from original cosmosis version
; omnuh2       =  0.00083
; massive_nu   =  3
; massless_nu  =  0.046

; New parametrization and names:
mnu = 0.323
num_massive_neutrinos = 3
nnu = 3.046

omega_k      =  0.0
tau          =  0.0697186

[shear_calibration_parameters]
m1 = -6.37553547e-03
m2 = -2.01975876e-02
m3 = -2.55440451e-02
m4 = -3.52015919e-02

[wl_photoz_errors]
bias_1 = 2.11727159e-03
bias_2 = -2.50423211e-03
bias_3 = -1.04078549e-03
bias_4 = 3.71136723e-03

[intrinsic_alignment_parameters]
z_piv   =  0.62
A1      = -9.93170530e-01
alpha1  = 2.30319420e+00
