[cosmological_parameters]
; omega_m      =  0.1     0.3     0.9
; use narrower range
omega_m      =  0.273859312
h0           =  0.758555441
omega_b      =  0.0436926338
n_s          =  0.963863327
w            =  -1.0

; This is here to test S_8 sampling, not to recommend it.
; Don't just put a flat prior on whatever the most convenient
; parameter is.
S_8          =  0.789742469

; Old parameter names from original cosmosis version
; omnuh2       =  0.0006  0.00083 0.00644
; massive_nu   =  3
; massless_nu  =  0.046

; New parametrization and names:
mnu = 0.263057514
num_massive_neutrinos = 3
; nnu = 3.046

omega_k      =  0.0
tau          =  0.0697186

[shear_calibration_parameters]
m1 = -0.00587736958
m2 = -0.0221175708
m3 = -0.0232803307
m4 = -0.0361818205

[wl_photoz_errors]
bias_1 = 0.00696653158
bias_2 = -0.0142430323
bias_3 =  0.00539263193
bias_4 = -0.00439672913

[intrinsic_alignment_parameters]
z_piv   =  0.62
A1      = -0.320054025
alpha1  = 2.33394373
