[cosmological_parameters]
; omega_m      =  0.1     0.3     0.9
; use narrower range
omega_m      =  0.2662
h0           =  0.7646
omega_b      = 0.043819
n_s          = 0.9769
w            =  -1.0

; This is here to test S_8 sampling, not to recommend it.
; Don't just put a flat prior on whatever the most convenient
; parameter is.
S_8          = 0.779898

; Old parameter names from original cosmosis version
; omnuh2       =  0.00083
; massive_nu   =  3
; massless_nu  =  0.046

; New parametrization and names:
mnu = 0.3019
num_massive_neutrinos = 3
nnu = 3.046

omega_k      =  0.0
tau          =  0.0697186

[shear_calibration_parameters]
m1 = -5.53900722e-03
m2 = -2.24016664e-02
m3 = -2.52608975e-02
m4 = -3.34147627e-02

[wl_photoz_errors]
bias_1 = 6.92271957e-03
bias_2 = -1.78888815e-02
bias_3 = -1.55636422e-03
bias_4 = 1.12536740e-02

[intrinsic_alignment_parameters]
z_piv   =  0.62
A1      = -2.90518927e-01
alpha1  = 2.56222670e+00
