[runtime]
; sampler = test
; sampler = multinest
sampler = list

[DEFAULT]
; 2PT_DATA_SETS = xip xim
; nz_file = 2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
; data_sets = source

[pipeline]
#values = config/fixed_vals.ini
; values = config/test-first-run/des-y3-shear-values-sim-cosmoGrid.ini 
values = config/emulator-train/values.ini
modules = consistency camb nz_source fastnc nc_to_map3
debug=T
timing=T
extra_output = map3/map3-bin_1_1_1#4 
               map3/map3-bin_2_2_2#4 
               map3/map3-bin_3_3_3#4 
               map3/map3-bin_4_4_4#4

[test]
save_dir=${COSMOSIS_3PCF_INTEGRATOR}/output/emulator-train
fatal_errors = T

[output]
filename=${COSMOSIS_3PCF_INTEGRATOR}/output/emulator-train

[nz_source]
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py
nz_file = ${COSMOSIS_3PCF_INTEGRATOR}/data/2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
data_sets = source

[source_photoz_bias]
file = ${COSMOSIS_STD_LIB}/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

[fastnc]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_interface.py
Lmax = 30
Mmax = 100
nfft = 150
projection=cent
sample_combinations = 1,1,1  2,2,2  3,3,3  4,4,4
dlnt = 0.253758
use-pixwin = T
nside = 1024
mu = 0 1 2 3
n-phi-bin = 60
phi-min = 0.01570796
phi-max = 3.12588469
n-theta-bin = 20
theta-min = 0.5
theta-max = 62.0703205
use_cache = T

[nc_to_map3]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/nc_to_map3.py
theta_filter_1 = 7.0 14.0 25.0 50.0
theta_filter_2 = 7.0 14.0 25.0 50.0
theta_filter_3 = 7.0 14.0 25.0 50.0
sample_combinations=1,1,1  2,2,2  3,3,3  4,4,4

[list]
filename = ${COSMOSIS_3PCF_INTEGRATOR}/data/nz/sobol_sequence_s8om.txt

; dependents
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmo.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/astrophysical.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/2pcf.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/linear-power.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/sampler.ini
