[runtime]
sampler = test
verbosity = standard

[DEFAULT]
2PT_FILE = ${COSMOSIS_3PCF_INTEGRATOR}/data/dv/sim_2pt-NLA.fits
MAP3_FILE = ${COSMOSIS_3PCF_INTEGRATOR}/data/dv/sim_map3-NLA.fits
run_name = TATT_test
group_name = test_TATT
output_dir = ${COSMOSIS_3PCF_INTEGRATOR}/output/%(GROUP_NAME)s

[pipeline]
modules =  consistency  bbn_consistency
           camb  fast_pt
           fits_nz  source_photoz_bias
           IA_NLA
           pk_to_cl
           add_intrinsic
           2pt_shear
           shear_m_bias
           map3_binning
           fastnc
           nc_to_map3
           ;fastnc_emulate
           save_map3
timing=T
debug=T
priors = ${COSMOSIS_STD_LIB}/examples/des-y3-priors.ini
values = ${COSMOSIS_3PCF_INTEGRATOR}/config/%(GROUP_NAME)s/DESY6_approx_vals.ini
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2
fast_slow = F
first_fast_module = shear_m_bias
; For some use cases this might be faster:
;first_fast_module=lens_photoz_width

[output]
filename = %(output_dir)s/des-y3-%(RUN_NAME)s.txt
format=text
privacy = F

[test]
save_dir=%(output_dir)s/des-y3-%(RUN_NAME)s
fatal_errors=T

%include ${COSMOSIS_3PCF_INTEGRATOR}/config/3pt.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/astrophysical.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmo.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmic-shear.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/linear-power.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/sampler.ini


; replace the settings of included files for this analysis
[map3_binning]
sample_combinations = all

[save_map3]
;filename = ${COSMOSIS_3PCF_INTEGRATOR}/data/dv/TATT_test_dvs/cosmo001-test-direct.fits
filename = ${COSMOSIS_3PCF_INTEGRATOR}/data/dv/TATT_test_dvs/DESY6_approx_vals_lowpivot.fits

[fastnc]
Lmax = 50
Mmax = 100
nfft = 150
projection=cent
dlnt = 0.253758
use-pixwin = T
nside = 1024
mu = 0 1 2 3
n-phi-bin = 60
phi-min = 0.01570796
phi-max = 3.12588469
n-theta-bin = 9
theta-min = 8.15147113
theta-max = 62.0703205
use_cache = T
save_multipoles = F
NLA = F
bispectrum_model = E_modes_TATT
