
[pk_to_cl]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/structure/projection/project_2d.py
ell_min_logspaced = 0.1
ell_max_logspaced = 5.0e5
n_ell_logspaced = 100
shear-shear = source-source
shear-intrinsic = source-source
intrinsic-intrinsic = source-source
intrinsicb-intrinsicb = source-source
verbose = F
get_kernel_peaks = F
sig_over_dchi = 20.
shear_kernel_dchi = 10.

;[2pt_shear]
;file = cosmosis-standard-library/shear/cl_to_xi_nicaea/nicaea_interface.so
;input_section_name = shear_cl
;output_section_name = shear_xi
;corr_type = 0

[2pt_shear]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = EB
theta_file = xxxyyy_Nov14.fits
bin_avg = T
input_section_name = shear_cl  shear_cl_bb
output_section_name = shear_xi_plus  shear_xi_minus

[2pt_like]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/likelihood/2pt/2pt_point_mass/2pt_point_mass.py
do_pm_marg = True
do_pm_sigcritinv = True
sigma_a = 10000.0
no_det_fac = False
include_norm = True
data_file = xxxyyy_Nov14.fits
data_sets = xip xim
make_covariance = F
covmat_name = COVMAT

;[2pt_like]
;file = cosmosis-standard-library/likelihood/2pt/2pt_like.py
;data_file = xxxyyy_Nov14.fits
;cut_zeros = T
;data_sets = shear
;do_plot = F
;gaussian_covariance=F
;number_density_shear_bin =  2.0  2.0  2.0  2.0  2.0
;number_density_lss_bin = 2.0  2.0  2.0
;sigma_e_bin = 0.2  0.2  0.2  0.2  0.2
;survey_area = 1500.0

[add_intrinsic]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/shear/add_intrinsic/add_intrinsic.py
shear-shear = T
position-shear = F
perbin = F

[add_magnification]
galaxy-galaxy=False

[shear_m_bias]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/shear/shear_bias/shear_m_bias.py
m_per_bin = True
cl_section = shear_xi_plus shear_xi_minus
cross_section = galaxy_shear_xi
verbose = F