[fastnc]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_interface.py
; maximum of multipoles to be considered
Lmax = 30
Mmax = 50
; size of FFT grid per dimension
nell12bin=150
; shear projection
projection=cent
; source 
sample_combinations = bin_1,bin_1,bin_1   bin_2,bin_2,bin_2   bin_3,bin_3,bin_3   bin_4,bin_4,bin_4
; index of natural components
mu = 0 1 2 3
; dlnt: bin width in log(theta1) = log(theta2) used in the measurement
; dlnt = 0.1 is a tentative place holder
dlnt = 0.1
; pixel window function
use-pixwin = T
nside = 1024