[fastnc]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_interface.py
; maximum of multipoles to be considered
Lmax = 30
Mmax = 100
; size of FFT grid per dimension
nfft = 150
; shear projection
projection=cent
; source 
sample_combinations = bin_1,bin_1,bin_1   bin_2,bin_2,bin_2   bin_3,bin_3,bin_3   bin_4,bin_4,bin_4
; dlnt: bin width in log(theta1) = log(theta2) used in the measurement
; dlnt = 0.1 is a tentative place holder
dlnt = 0.253758
; 0.2671
#0.1
; pixel window function
use-pixwin = T
nside = 1024
; index of natural components
mu = 0 1 2 3
; phi bin (number, radian, radian),
n-phi-bin = 60
phi-min = 0.01570796
phi-max = 3.12588469
; tentative scale cuts applied on theory Gamma, in arcmin
n-theta-bin = 20
theta-min = 0.5
theta-max = 62.0703205
; theta-max = 80.0

[map3_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/map3_likelihood.py
; path_chains =  data/nz/map3_dv_COSMOGRID_7Mar24_REDSHIFT_AUTOCORRELATIONS_ONLY
path_chains = %(MAP3_FILE)s
theta_filter_1 = 7.0 14.0 25.0 50.0
theta_filter_2 = 7.0 14.0 25.0 50.0
theta_filter_3 = 7.0 14.0 25.0 50.0
sample_combinations=bin_1,bin_1,bin_1 bin_2,bin_2,bin_2 bin_3,bin_3,bin_3 bin_4,bin_4,bin_4