[fastnc]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_interface.py
; maximum of multipoles to be considered
Lmax = 30
Mmax = 50
; size of FFT grid per dimension
nell12bin=150
; shear projection
shear-projection=x
