[map3_binning]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/map3_binning.py
data_file = %(MAP3_FILE)s
sample_combinations = all

[fastnc]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_interface.py
Lmax = 30
Mmax = 100
nfft = 150
projection=cent
dlnt = 0.253758
use-pixwin = T
nside = 1024
mu = 0 1 2 3
n-phi-bin = 60
phi-min = 0.01570796
phi-max = 3.12588469
n-theta-bin = 20
theta-min = 0.5
theta-max = 62.0703205
use_cache = F
NLA = T

[nc_to_map3]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/nc_to_map3.py

[map3_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/map3_likelihood.py
data_file = %(MAP3_FILE)s

[save_map3]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/save_map3.py
; filename = data/nz/sim_map3_baryon_OWLS.fits
copy_covariance = %(MAP3_FILE)s
