[map3_binning]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/map3_binning.py
data_file = %(MAP3_FILE)s
sample_combinations = all

[fastnc]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_interface.py
Lmax = 50
Mmax = 100
nfft = 150
projection=cent
dlnt = 0.253758
use-pixwin = T
nside = 1024
mu = 0 1 2 3
n-phi-bin = 63
phi-min = 0.01570796
phi-max = 3.12588469
n-theta-bin = 20
theta-min = 0.5
theta-max = 62.0703205
use_cache = T
NLA = T

[nc_to_map3]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/nc_to_map3.py

[map3_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/map3_likelihood.py
data_file = %(MAP3_FILE)s

[save_map3]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/save_map3.py
; filename = data/nz/sim_map3_baryon_OWLS.fits
copy_covariance = %(MAP3_FILE)s

[fastnc_emulate_v1]
; version 1
; this is an emulator replacement of fastnc + nc_to_map3 modules
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_emulate.py
theta_filter_1 = 7.0 14.0 25.0 40.0
theta_filter_2 = 7.0 14.0 25.0 40.0
theta_filter_3 = 7.0 14.0 25.0 40.0
z_values = 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1.0 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4
model_filename = data/nz/map3_model_28zs-2
rescaling_filename = data/nz/rescaling_for_map3_network_28zs.pkl

[fastnc_emulate]
; version 2 with finer redshift bins
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_emulate.py
theta_filter_1 = 7.0 14.0 25.0 40.0
theta_filter_2 = 7.0 14.0 25.0 40.0
theta_filter_3 = 7.0 14.0 25.0 40.0
z_values = 0.005 0.01 0.02 0.03 0.04 0.05 0.07 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1.0 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5
model_filename = data/train_emulator/map3_model_13May24-0
rescaling_filename = data/train_emulator/rescaling_for_map3_network_13May24.pkl
nz_upsampling = 100
