[DEFAULT]
; baseline_dir = .
; datavector_dir = .
; 2pt_file = ../data/des-y3/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate.fits
2pt_file = ${COSMOSIS_STD_LIB}/likelihood/des-y3/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate.fits
map3_file = ${COSMOSIS_3PCF_INTEGRATOR}/data/nz/map3_synthetic_desy3-param_REDSHIFT_AUTOCORRELATIONS_ONLY
2pt_data_sets = xip xim
run_name = 2pt-map3-s8om

[runtime]
; sampler = polychord
; root = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis/
sampler = multinest
; sampler = test

[multinest]
max_iterations = 50000
multinest_outfile_root = output/chain_checkpoints/mn_%(RUN_NAME)s
resume = F
live_points = 500
efficiency = 0.3
tolerance = 0.01
constant_efficiency = F

[polychord]
base_dir = chain_checkpoints
polychord_outfile_root = poly_%(RUN_NAME)s
resume = F
feedback = 3
fast_fraction = 0.1
live_points = 500
num_repeats = 60
tolerance = 0.01
boost_posteriors = 10.0

[output]
; filename = chain_%(RUN_NAME)s.txt
filename = output/chain_%(RUN_NAME)s.txt
format = text
lock = F
privacy = F

[emcee]
walkers = 100
samples = 1000
nsteps = 5

[star]
nsample_dimension = 50

[test]
; save_dir = %(RUN_NAME)s/test_%(RUN_NAME)s
save_dir = output/test_%(RUN_NAME)s
fatal_errors = T

[pipeline]
modules = consistency bbn_consistency camb_halofit extrapolate fits_nz lens_photoz_bias lens_photoz_width fast_pt source_photoz_bias IA pk_to_cl add_intrinsic add_eb shear_2pt_eplusb shear_2pt_eminusb choose_xip 2pt_gal_shear shear_m_bias  smallratio_like 2pt_like fastnc map3_like
likelihoods = 2pt smallratio
quiet = F
timing = T
debug = T
; priors = fiducial/priors.ini
; values = fiducial/values.ini
priors = ${COSMOSIS_3PCF_INTEGRATOR}/config/des-y3-shear-2pt-priors.ini
values = ${COSMOSIS_3PCF_INTEGRATOR}/config/des-y3-shear-2pt-values-s8om.ini
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2
fast_slow = T
first_fast_module = shear_m_bias

%include ${COSMOSIS_3PCF_INTEGRATOR}/config/3pcf.ini

[consistency]
; file = cosmosis-standard-library/utility/consistency/consistency_interface.py
file = ${COSMOSIS_STD_LIB}/utility/consistency/consistency_interface.py

; [camb]
; file = cosmosis-standard-library/boltzmann/camb/camb.so
; file = ${COSMOSIS_STD_LIB}/boltzmann/camb/camb_interface.py
; mode = all
; lmax = 2500
; feedback = 0
; kmin = 1e-5
; kmax = 100.0
; nk = 400

[camb_planck]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode = all
lmax = 3000
feedback = 0
do_tensors = T
do_lensing = T
do_nonlinear = T
high_ell_template = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-standard-library/boltzmann/camb/camb_Jan15/HighLExtrapTemplate_lenspotentialCls.dat
accuracy_boost = 1.1
high_accuracy_default = T

[camb_planck_lensing]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode = all
lmax = 4500
feedback = 0
do_lensing = T
do_nonlinear = T
use_nonlinear_lensing = T
high_ell_template = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-standard-library/boltzmann/camb/camb_Jan15/HighLExtrapTemplate_lenspotentialCls.dat
accuracy_boost = 1.
high_accuracy_default = T
k_eta_max_scalar = 500000

; [halofit]
; file = cosmosis-standard-library/boltzmann/halofit_takahashi/halofit_interface.so
; nk = 700

; camb and takahashi
[camb_halofit]
file = ${COSMOSIS_STD_LIB}/boltzmann/camb/camb_interface.py
mode = all
lmax = 3000          ;max ell to use for cmb calculation
feedback=3         ;amount of output to print
AccuracyBoost=1.1 ;CAMB accuracy boost parameter
do_tensors = T
do_lensing = T
NonLinear = pk
halofit_version = takahashi
zmin_background = 0.
zmax_background = 4.
nz_background = 401
kmin=1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk=700

[bbn_consistency]
; file = cosmosis-standard-library/utility/bbn_consistency/bbn_consistency.py
file = ${COSMOSIS_STD_LIB}/utility/bbn_consistency/bbn_consistency.py

[extrapolate]
; file = cosmosis-standard-library/boltzmann/extrapolate/extrapolate_power.py
file = ${COSMOSIS_STD_LIB}/boltzmann/extrapolate/extrapolate_power.py
kmax = 500.

[fits_nz]
; file = cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py
nz_file = %(2PT_FILE)s
data_sets = lens source
prefix_section = T
prefix_extension = T

[fits_nz_lens]
; file = cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py
nz_file = %(2PT_FILE)s
data_sets = lens
prefix_section = T
prefix_extension = T

[lens_photoz_width]
; file = cosmosis-des-library/photoz/photoz_width.py
file = ${COSMOSIS_DES_LIB}/photoz/photoz_width.py
mode = stretch
sample = nz_lens
bias_section = lens_photoz_errors
interpolation = linear

[lens_photoz_bias]
; file = cosmosis-standard-library/number_density/photoz_bias/photoz_bias.py
file = ${COSMOSIS_STD_LIB}/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_lens
bias_section = lens_photoz_errors
interpolation = linear

[hyperrank]
; file = cosmosis-standard-library/number_density/nz_multirank/nz_multirank.py
file = ${COSMOSIS_STD_LIB}/number_density/nz_multirank/nz_multirank.py
nz_file = %(2PT_FILE)s
data_set = source
dimensions = 3
bin_ranks = 1 2 4

[source_photoz_bias]
; file = cosmosis-standard-library/number_density/photoz_bias/photoz_bias.py
file = ${COSMOSIS_STD_LIB}/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

[fast_pt]
; file = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-des-library/tcp/fast_pt/fast_pt_interface.py
file = ${COSMOSIS_STD_LIB}/structure/fast_pt/fast_pt_interface.py
do_ia = T
k_res_fac = 0.5
verbose = F

[IA]
; file = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-des-library/IAs/tatt/tatt_interface.py
file = ${COSMOSIS_DES_LIB}/IAs/tatt/tatt_interface.py
sub_lowk = F
sub_const = F
include_s2_terms = F
do_galaxy_intrinsic = F
ia_model = tatt
asigma8 = F
linterp = F

[pk_to_cl_gg]
; file = cosmosis-standard-library/structure/projection/project_2d.py
file = ${COSMOSIS_STD_LIB}/structure/projection/project_2d.py
lingal-lingal = lens-lens
do_exact = lingal-lingal
do_rsd = True
ell_min_linspaced = 1
ell_max_linspaced = 4
n_ell_linspaced = 5
ell_min_logspaced = 5.
ell_max_logspaced = 1.e5
n_ell_logspaced = 80
limber_ell_start = 200
auto_only = lingal-lingal
sig_over_dchi_exact = 3.5

[pk_to_cl]
; file = cosmosis-standard-library/structure/projection/project_2d.py
file = ${COSMOSIS_STD_LIB}/structure/projection/project_2d.py
ell_min_logspaced = 0.1
ell_max_logspaced = 5.0e5
n_ell_logspaced = 100
shear-shear = source-source
shear-intrinsic = source-source
intrinsic-intrinsic = source-source
intrinsicb-intrinsicb = source-source
lingal-shear = lens-source
lingal-intrinsic = lens-source
lingal-magnification =
magnification-shear = lens-source
magnification-magnification =
magnification-intrinsic = lens-source
verbose = F
get_kernel_peaks = F
sig_over_dchi = 20.
shear_kernel_dchi = 10.

[add_magnification]
; file = cosmosis-standard-library/structure/projection/add_magnification.py
file = ${COSMOSIS_STD_LIB}/structure/magnification/add_magnification.py
include_intrinsic = T
galaxy-galaxy = False

[add_intrinsic]
; file = cosmosis-standard-library/shear/add_intrinsic/add_intrinsic.py
file = ${COSMOSIS_STD_LIB}/shear/add_intrinsic/add_intrinsic.py
shear-shear = T
position-shear = T
perbin = F

[add_eb]
; file = cosmosis-des-library/IAs/add_bmode_cl/add_bmode_cl.py
file = ${COSMOSIS_DES_LIB}/IAs/add_bmode_cl/add_bmode_cl.py

[shear_2pt_eplusb]
; file = cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
file = ${COSMOSIS_STD_LIB}/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = '22'
theta_file = %(2PT_FILE)s
bin_avg = T
input_section_name = shear_cl_eplusb
output_section_name = shear_xi_eplusb

[shear_2pt_eminusb]
; file = cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
file = ${COSMOSIS_STD_LIB}/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = '22'
theta_file = %(2PT_FILE)s
bin_avg = T
input_section_name = shear_cl_eminusb
output_section_name = shear_xi_eminusb

[choose_xip]
; file = cosmosis-standard-library/utility/tools/copy_section.py
file = ${COSMOSIS_STD_LIB}/utility/copy/copy_section.py
source = shear_xi_eplusb_plus   shear_xi_eminusb_minus
dest = shear_xi_plus          shear_xi_minus

[2pt_gal]
; file = cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
file = ${COSMOSIS_STD_LIB}/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = '00'
theta_file = %(2PT_FILE)s
bin_avg = T

[2pt_gal_shear]
; file = cosmosis-standard-library/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
file = ${COSMOSIS_STD_LIB}/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = '02'
theta_file = %(2PT_FILE)s
bin_avg = T

[shear_m_bias]
; file = cosmosis-standard-library/shear/shear_bias/shear_m_bias.py
file = ${COSMOSIS_STD_LIB}/shear/shear_bias/shear_m_bias.py
m_per_bin = True
cl_section = shear_xi_plus shear_xi_minus
cross_section = galaxy_shear_xi
verbose = F

[add_pm]
file = cosmosis-des-library/tcp/pm_marg/addpm_to_gammat.py
add_togammat = False
use_fiducial = True

[2pt_like]
; file = cosmosis-standard-library/likelihood/2pt/2pt_like_allmarg.py
file = ${COSMOSIS_STD_LIB}/likelihood/2pt/2pt_like.py
do_pm_marg = True
do_pm_sigcritinv = True
sigma_a = 10000.0
no_det_fac = False
include_norm = True
data_file = %(2PT_FILE)s
data_sets = %(2PT_DATA_SETS)s
make_covariance = F
covmat_name = COVMAT
angle_range_xip_1_1 = 2.475 999.0
angle_range_xip_1_2 = 2.475 999.0
angle_range_xip_1_3 = 3.116 999.0
angle_range_xip_1_4 = 2.475 999.0
angle_range_xip_2_2 = 3.923 999.0
angle_range_xip_2_3 = 4.938 999.0
angle_range_xip_2_4 = 4.938 999.0
angle_range_xip_3_3 = 3.923 999.0
angle_range_xip_3_4 = 4.938 999.0
angle_range_xip_4_4 = 3.923 999.0
angle_range_xim_1_1 = 24.750 999.0
angle_range_xim_1_2 = 19.660 999.0
angle_range_xim_1_3 = 24.750 999.0
angle_range_xim_1_4 = 19.660 999.0
angle_range_xim_2_2 = 31.158 999.0
angle_range_xim_2_3 = 39.226 999.0
angle_range_xim_2_4 = 39.226 999.0
angle_range_xim_3_3 = 49.383 999.0
angle_range_xim_3_4 = 49.383 999.0
angle_range_xim_4_4 = 39.226 999.0
angle_range_gammat_1_1 = 24.75 999.0
angle_range_gammat_1_2 = 24.75 999.0
angle_range_gammat_1_3 = 24.75 999.0
angle_range_gammat_1_4 = 24.75 999.0
angle_range_gammat_2_1 = 15.61619428 999.0
angle_range_gammat_2_2 = 15.61619428 999.0
angle_range_gammat_2_3 = 15.61619428 999.0
angle_range_gammat_2_4 = 15.61619428 999.0
angle_range_gammat_3_1 = 12.40438403 999.0
angle_range_gammat_3_2 = 12.40438403 999.0
angle_range_gammat_3_3 = 12.40438403 999.0
angle_range_gammat_3_4 = 12.40438403 999.0
angle_range_gammat_4_1 = 12.40438403 999.0
angle_range_gammat_4_2 = 12.40438403 999.0
angle_range_gammat_4_3 = 12.40438403 999.0
angle_range_gammat_4_4 = 12.40438403 999.0
angle_range_gammat_5_1 = 9.85315247 999.0
angle_range_gammat_5_2 = 9.85315247 999.0
angle_range_gammat_5_3 = 9.85315247 999.0
angle_range_gammat_5_4 = 9.85315247 999.0
angle_range_wtheta_1_1 = 39.22610651 999.0
angle_range_wtheta_2_2 = 24.75 999.0
angle_range_wtheta_3_3 = 19.65962381 999.0
angle_range_wtheta_4_4 = 15.61619428 999.0
angle_range_wtheta_5_5 = 12.40438403 999.0

[smallratio_like]
name_likelihood = smallratio_like
; file = cosmosis-des-library/shearratio_like/ratio_likelihood.py
file = ${COSMOSIS_DES_LIB}/shearratio_like/ratio_likelihood.py
save_ratio_filename = none
; measured_ratio_filename = ../data/des-y3/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate_sr.npy
; measured_ratio_filename = ${COSMOSIS_STD_LIB}/likelihood/des-y3/shear_ratio/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate_sr.npy
measured_ratio_filename = ${COSMOSIS_STD_LIB}/likelihood/des-y3/shear_ratio/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate_sr.npy
gglensing_section = galaxy_shear_xi
th_limit_low_s14 = 8.47 6.07 4.34 2.5 2.5 2.5
th_limit_low_s24 = 8.47 6.07 4.34 2.5 2.5 2.5
th_limit_low_s34 = 2.5 2.5 4.34 2.5 2.5 2.5
th_limit_high = 25.4 18.26 13.03 10.87 9.66 9.04
lens_bins = 3

[save_2pt]
file = cosmosis-standard-library/likelihood/2pt/save_2pt.py
theta_min = 2.5
theta_max = 250.0
n_theta = 20
real_space = T
make_covariance = F
shear_nz_name = nz_source
position_nz_name = nz_lens
filename = data_vectors/sim_%(RUN_NAME)s.fits
overwrite = T
auto_only = galaxy_xi
spectrum_sections = shear_xi_plus shear_xi_minus galaxy_shear_xi galaxy_xi
output_extensions = xip xim gammat wtheta
two_thirds_midpoint = T
copy_covariance = data_vectors/des-y3/2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate.fits

[sim_fits_nz_lens]
file = cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
nz_file = nz_inputs/nz_y3_redmagic_v6.4.22_v2_gold_2.2.1_combined_max_bin_edges.fits
data_sets = lens
prefix_section = T
prefix_extension = T

[sim_fits_nz_source]
file = cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
nz_file = nz_inputs/barcelona_lens1.fits
data_sets = source
prefix_section = T
prefix_extension = T

[p-TTTEEE-lowE]
file = cosmosis-standard-library/likelihood/planck2018/planck_interface.so
data_1 = ${PLANCKPATH}/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik
data_2 = ${PLANCKPATH}/low_l/commander/commander_dx12_v3_2_29.clik
data_3 = ${PLANCKPATH}/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik

[p-TTTEEE_lite-lowE]
file = cosmosis-standard-library/likelihood/planck2018/planck_interface.so
data_1 = ${PLANCKPATH}/hi_l/plik_lite/plik_lite_v22_TTTEEE.clik
data_2 = ${PLANCKPATH}/low_l/commander/commander_dx12_v3_2_29.clik
data_3 = ${PLANCKPATH}/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik

[p-TTTEEE-lowE-lensing]
file = cosmosis-standard-library/likelihood/planck2018/planck_interface.so
data_1 = ${PLANCKPATH}/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik
data_2 = ${PLANCKPATH}/low_l/commander/commander_dx12_v3_2_29.clik
data_3 = ${PLANCKPATH}/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik
lensing_1 = ${PLANCKPATH}/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing

[p-lensing]
file = cosmosis-standard-library/likelihood/planck2018/planck_interface.so
lensing_1 = ${PLANCKPATH}/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8_CMBmarged.clik_lensing

[6dfgs]
file = cosmosis-standard-library/likelihood/6dfgs/6dfgs.py
bao_mode = "rs_dv"

[mgs_bao]
file = cosmosis-standard-library/likelihood/mgs_bao/mgs_bao.py

[bossdr12_gal]
file = cosmosis-standard-library/likelihood/boss_dr12/boss_dr12.py
mode = 0
feedback = 0

[bossdr12_reanalyze]
file = cosmosis-standard-library/likelihood/eboss_dr16/boss_dr12/boss_dr12_lrg_reanalyze.py
mode = 0
feedback = F

[bao_desy3]
file = cosmosis-des-library/lss/bao_y3_like/bao_y3_like.py

[bao_desy1]
file = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-des-library/lss/bao_y1_like/bao_y1_like.py

[eboss16_lrg]
file = cosmosis-standard-library/likelihood/eboss_dr16/lrg/eboss_dr16_lrg.py
mode = 0
feedback = F

[eboss16_elg]
file = cosmosis-standard-library/likelihood/eboss_dr16/elg/eboss_dr16_elg.py
mode = 0
feedback = F

[eboss16_qso]
file = cosmosis-standard-library/likelihood/eboss_dr16/qso/eboss_dr16_qso.py
mode = 0
feedback = F

[eboss16_lya]
file = cosmosis-standard-library/likelihood/eboss_dr16/lya/eboss_dr16_lya.py
feedback = F

[pantheon]
file = cosmosis-standard-library/likelihood/pantheon/pantheon.py

[riess16]
file = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-standard-library/likelihood/riess16/riess16.py

[des_sne]
file = /home/users/amon2018/risahw/amon2018/intelpython3/cosmosis//cosmosis-standard-library/likelihood/pantheon/pantheon.py
data_file = ../data/Y1_DESSN_ONLY_COSMOSIS_FILES/lcparam_DESONLY_V8_0.txt
covmat_file = ../data/Y1_DESSN_ONLY_COSMOSIS_FILES/sys_DESONLY_V8_AVG_0.txt

[6dfgs_baorsd]
file = cosmosis-standard-library/external/bao/6dfgs/6dfgs.py
rsd_like = T

[mgs_baorsd]
file = cosmosis-standard-library/likelihood/eboss_dr16/mgs/mgs.py

[bossdr12_reanalyze_baorsd]
file = cosmosis-standard-library/likelihood/eboss_dr16/boss_dr12/boss_dr12_lrg_reanalyze.py
mode = 1
feedback = F

[eboss16_lrg_baorsd]
file = cosmosis-standard-library/likelihood/eboss_dr16/lrg/eboss_dr16_lrg.py
mode = 1
feedback = F

[eboss16_elg_baorsd]
file = cosmosis-standard-library/likelihood/eboss_dr16/elg/eboss_dr16_elg.py
mode = 1
feedback = F

[eboss16_qso_baorsd]
file = cosmosis-standard-library/likelihood/eboss_dr16/qso/eboss_dr16_qso.py
mode = 1
feedback = F

[bbn]
file = cosmosis-standard-library/likelihood/bbn/bbn_ombh2_pitoru20_cooke18/bbn_ombh2_pitrou20_cooke18.py
