; 2pt-only moped compression
[2pt_moped_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/moped_likelihood.py
likelihoods = 2pt
data_file = ${COSMOSIS_3PCF_INTEGRATOR}/data/moped/moped-moped-compress-2pt.txt
like_name = 2pt_moped

; 3pt-only moped compression
[map3_moped_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/moped_likelihood.py
likelihoods = map3
data_file = ${COSMOSIS_3PCF_INTEGRATOR}/data/moped/moped-moped-compress-map3-all.txt
like_name = map3_moped

; joint moped compression
[joint_moped_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/moped_likelihood.py
likelihoods = joint
data_file = ${COSMOSIS_3PCF_INTEGRATOR}/data/moped/moped-moped-compress-2pt-map3-all.txt
like_name = joint_moped
