[multinest]
;wrapped_params = cosmological_parameters--omega_b   cosmological_parameters--h0
max_iterations=5000
;max_iterations = 1000
multinest_outfile_root=mn_LCDM_10Jan24smallerDV_2plus3
resume=F
; from Joe:- For a quick run:
live_points=250
efficiency=0.8
tolerance=0.1
constant_efficiency=F

#my trial
[polychord]
;base_dir = output/y3-polychord-checkpoints
polychord_outfile_root = pl_LCDM_10Jan24_2plus3
resume = F
feedback = 3
fast_fraction = 0.1
live_points = 250
num_repeats = 60
tolerance = 0.05
boost_posteriors = 10.0