[runtime]
; sampler = multinest
; sampler = polychord
sampler = test

[DEFAULT]
2PT_DATA_SETS = xip xim
nz_file = 2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
data_sets = source

[pipeline]
values = fixed_vals.ini
modules = fits_nz shear_3PCF_like
quiet=F
debug=T
timing=T

[output]
filename=my_2plus3pt_LCDM_10Jan24_smallerDV_chain.txt
format=text

[fast_pt]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/structure/fast_pt/fast_pt_interface.py
do_ia = T
k_res_fac = 0.5
verbose = F

[growth]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/structure/growth_factor/interface.so
zmin = 0.
zmax = 4.
nz = 401

[fits_nz]
; file = #/Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/number_density/load_nz_fits/load_nz_fits.py
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py

[IA]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/intrinsic_alignments/tatt/tatt_interface.py
sub_lowk = F
do_galaxy_intrinsic = F
ia_model = tatt

[shear_3PCF_like]
file = /Users/gchgomes/Downloads/3PCF_likelihood_smaller.py
path_chains =  Sep12_datavector
key =  all_data

[source_photoz_bias]
file = /Users/gchgomes/PycharmProjects/bispectrum_integrator/cosmosis-standard-library/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear