[runtime]
sampler = test

[DEFAULT]
; 2PT_DATA_SETS = xip xim
; nz_file = 2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
; data_sets = source

[pipeline]
values = fixed_vals.ini
modules = fastnc
quiet=F
debug=T
timing=T

[output]
filename=fastnc
format=text

[fits_nz]
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py

[source_photoz_bias]
file = ${COSMOSIS_STD_LIB}/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

; dependents
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/cosmo.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/astrophysical.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/2pcf.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/linear-power.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/background.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/3pcf.ini
%include ${COSMOSIS_3PCF_INTEGRATOR}/config/sampler.ini