[runtime]
;sampler = multinest
sampler = test

[DEFAULT]
2PT_DATA_SETS = xip xim
nz_file = data/2pt_NG_final_2ptunblind_02_24_21_wnz_redmagic_covupdate.fits
data_sets = source

[pipeline]
;values = config/valuesLCDMrafa.ini
values = config/fixed_vals.ini
modules = consistency camb fast_pt fits_nz  source_photoz_bias IA  pk_to_cl add_intrinsic 2pt_shear shear_m_bias 2pt_like emu_map3_like
likelihoods = 2pt emu_map3
timing=T
debug=T

[test]
save_dir=output/2pt-plus-3pt-emu19Apr
fatal_errors = T

[multinest]
max_iterations=2000
multinest_outfile_root=mn_2pt_plus_map3_FIRST_RUN_21Mar
resume=F
; from Joe:- For a quick run:
live_points=250
efficiency=0.8
tolerance=0.1
;constant_efficiency=F
constant_efficiency=T

[output]
filename=2pt_plus_map3_emu19Apr.txt
format=text

[consistency]
file = ${COSMOSIS_STD_LIB}/utility/consistency/consistency_interface.py

[camb]
file = ${COSMOSIS_STD_LIB}/boltzmann/camb/camb_interface.py
mode = power
lmax = 2500
feedback = 3
accuracyboost = 1.1
do_tensors = T
do_lensing = T
nonlinear = pk
halofit_version = takahashi
zmin_background = 0.
zmax_background = 4.
nz_background = 401
kmin = 1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk = 700

[sigma8toAs]
file = ${COSMOSIS_STD_LIB}/kids/sigma8toAs.py

[fast_pt]
file = ${COSMOSIS_STD_LIB}/structure/fast_pt/fast_pt_interface.py
do_ia = T
k_res_fac = 0.5
verbose = F

[growth]
file = ${COSMOSIS_STD_LIB}/structure/growth_factor/interface.so
zmin = 0.
zmax = 4.
nz = 401

[extrapolate]
file = ${COSMOSIS_STD_LIB}/boltzmann/extrapolate/extrapolate_power.py

[fits_nz]
file = ${COSMOSIS_STD_LIB}/number_density/load_nz_fits/load_nz_fits.py

[IA]
file = ${COSMOSIS_STD_LIB}/intrinsic_alignments/tatt/tatt_interface.py
sub_lowk = F
do_galaxy_intrinsic = F
ia_model = tatt

[pk_to_cl]
file = ${COSMOSIS_STD_LIB}/structure/projection/project_2d.py
ell_min_logspaced = 0.1
ell_max_logspaced = 5.0e5
n_ell_logspaced = 100
shear-shear = source-source
shear-intrinsic = source-source
intrinsic-intrinsic = source-source
intrinsicb-intrinsicb = source-source
verbose = F
get_kernel_peaks = F
sig_over_dchi = 20.
shear_kernel_dchi = 10.

[2pt_shear]
file = ${COSMOSIS_STD_LIB}/shear/cl_to_xi_fullsky/cl_to_xi_interface.py
ell_max = 40000
xi_type = EB
theta_file = data/nz/DATA_AND_COV_FOR_2pt_COSMOGRID_400_NOISELESS_SIMS.fits
bin_avg = T
input_section_name = shear_cl  shear_cl_bb
output_section_name = shear_xi_plus  shear_xi_minus

[shear_m_bias]
file = ${COSMOSIS_STD_LIB}/shear/shear_bias/shear_m_bias.py
m_per_bin = True
cl_section = shear_xi_plus shear_xi_minus
cross_section = galaxy_shear_xi
verbose = F

[2pt_like]
file = ${COSMOSIS_STD_LIB}/likelihood/2pt/2pt_point_mass/2pt_point_mass.py
do_pm_marg = True
do_pm_sigcritinv = True
sigma_a = 10000.0
no_det_fac = False
include_norm = True
data_file = data/nz/DATA_AND_COV_FOR_2pt_COSMOGRID_400_NOISELESS_SIMS.fits
data_sets = xip xim
make_covariance = F
covmat_name = COVMAT

[emu_map3_like]
file = ${COSMOSIS_3PCF_INTEGRATOR}/python/fastnc_emulate.py
path_chains =  data/nz/map3_dv_COSMOGRID_19Apr24
; maximum of multipoles to be considered
Lmax = 100
theta_filter_1 = 7.0 14.0 25.0 40.0
theta_filter_2 = 7.0 14.0 25.0 40.0
theta_filter_3 = 7.0 14.0 25.0 40.0
z_values = 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1.0 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4
z_values = 0.01 0.02 0.03 0.04 0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1.0 1.05 1.1 1.15 1.2 1.25 1.3 1.35 1.4 1.45 1.5
;model_filename = data/nz/map3_model_28zs-2
model_filename = data/nz/map3_model_34zs-0
;rescaling_filename = data/nz/rescaling_for_map3_network_28zs.pkl
rescaling_filename = data/nz/rescaling_for_map3_network_34zs.pkl
sample_combinations= 1,1,1 1,1,2 1,1,3 1,1,4 1,2,2 1,2,3 1,2,4 1,3,3 1,3,4 1,4,4 2,2,2 2,2,3 2,2,4 2,3,3 2,3,4 2,4,4 3,3,3 3,3,4 3,4,4 4,4,4

[source_photoz_bias]
file = ${COSMOSIS_STD_LIB}/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_source
bias_section = wl_photoz_errors
interpolation = linear

[add_intrinsic]
file = ${COSMOSIS_STD_LIB}/shear/add_intrinsic/add_intrinsic.py
shear-shear = T
position-shear = F
perbin = F

[sigma8_rs]
file=cosmosis-standard-library/utility/sample_sigma8/sigma8_rescale.py

[add_magnification]
galaxy-galaxy=False

